# Generated by Django 3.2.3 on 2025-01-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngridient',
            new_name='RecipeIngredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
