# Generated by Django 3.2.3 on 2025-01-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250119_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
    ]
