# Generated by Django 3.2.3 on 2025-01-19 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='[^\\w.@+-]')], verbose_name='Логин'),
        ),
    ]
